### ISSUE TITLE
[Enhancement]: release 0.8.6 sooner possible

### ISSUE THREAD

**Issue by PavanLuca** [snapcrafters/xonotic#17]
### What changes would you like?

Versions older than 0.8.6 are a risk when multiplaying.
https://xonotic.org/download/#older-downloads

**Comment by eslerm** [comment]
Updates to fix the security are merged, but not yet built https://snapcraft.io/xonotic

Could a Snapcrafter please run a new build to close this issue?

**Comment by PavanLuca** [comment]
I don't know snaps and flats update procedures so instead of waiting an unknown or unreasonable amount of time I installed the flat version some days after.

**Comment by eslerm** [comment]
@NucciTheBoss could you please trigger a rebuild or ping other snapcrafters :pray:

**Comment by tobhe** [comment]
ping @NucciTheBoss @lucyllewy @popey could you please push this to stable?

**Comment by NucciTheBoss** [comment]
@eslerm @tobhe I don't have the relevant permissions to modify the xonotic available in the Snap Store. I'm not sure who directly controls the uploads for the store, so I am not sure that I will be much help here unless I request that the Xonotic snap be transferred to me and other crafters on the Snapcraft forum.

**Comment by tobhe** [comment]
ping once more. Can I apply for maintainership of this snap somewhere?

**Comment by lucyllewy** [comment]
Hi,

I don't have an AMD64 machine with me right now as I am away from my main PC. Can you confirm that the revision in the edge channel works so that I may push it to stable with more confidence?

You can update to the edge channel for this with the following command:

´´´bash
sudo snap refresh --edge xonotic
´´´

You can switch back again once you've verified it works with:

´´´bash
sudo snap refresh --stable xonotic
´´´

**Comment by eslerm** [comment]
Thank you!

I attempted `sudo snap install --edge xonotic`, but received an error stating that the arm64 architecture is not available on edge.

**Comment by popey** [comment]
![xonotic20231004164946-00](https://github.com/snapcrafters/xonotic/assets/1841272/a62e0616-ed76-4111-9cea-4ecb441b7f78)

amd64 works for me.

**Comment by tobhe** [comment]
Works here on my amd64 desktop too. No screenshot because my score is embarrassing compared with @popey's.

**Comment by lucyllewy** [comment]
I've pushd the revision to stable. Thank you for your assistance in verifying it works well.

**Comment by tobhe** [comment]
Is there anything still missing to also build for arm64? In theory it should be enabled since my last commit but I do remember from another snap that launchpad had problems picking it up automatically, see https://github.com/dclane-code/ghidra-snap/commit/4c0a2e6fa6126f24e4a1eafbadf7d084130a2f13.

**Comment by eslerm** [comment]
that sounds like a second pr and an upstream issue :(
