### ISSUE TITLE
Bad FPS when running snap under AMD [unplayable]

### ISSUE THREAD

**Issue by kaincenteno** [snapcrafters/xonotic#7]
Using an AMD APU (Ryzen 4700U laptop) when launching xonotic with the snap makes graphics have a really bad FPS.
On terminal i see

```
libGL error: pci id for fd 11: 1002:1636, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 11: 1002:1636, driver (null)
pci id for fd 12: 1002:1636, driver (null)
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
```
and
```
GL_VENDOR: VMware, Inc.
GL_RENDERER: llvmpipe (LLVM 6.0, 128 bits)
GL_VERSION: 3.0 Mesa 18.0.5
```

When launching the non-snap version, there is no issues with graphics and have a great FPS.
On terminal i see
```
GL_VENDOR: X.Org
GL_RENDERER: AMD RENOIR (DRM 3.38.0, 5.8.0-40-generic, LLVM 11.0.0)
GL_VERSION: 4.6 (Compatibility Profile) Mesa 20.2.6
```

This issue cannot be reproduced using a Intel CPU, only seems to be an issue with AMD. (I'm using the open drivers)

**Comment by eslerm** [comment]
This is no longer an issue.

Snap runs great on a AMD Ryzen 7 PRO 5850U with Radeon Graphics laptop and a Ryzen 5 1600 and AMD Radeon RX Vega 56 desktop.

**Comment by kenvandine** [comment]
Thanks
